import {
  APP_ENV_FIREBASE_API_KEY,
  APP_ENV_FIREBASE_AUTH_DOMAIN,
  APP_ENV_FIREBASE_PROJECT_ID,
  APP_ENV_FIREBASE_STORE_BUCKET,
  APP_ENV_FIREBASE_MESSAGING_SENDER_ID,
  APP_ENV_FIREBASE_APP_ID,
} from "@env";

export default {
  APP_ENV_FIREBASE_API_KEY,
  APP_ENV_FIREBASE_AUTH_DOMAIN,
  APP_ENV_FIREBASE_PROJECT_ID,
  APP_ENV_FIREBASE_STORE_BUCKET,
  APP_ENV_FIREBASE_MESSAGING_SENDER_ID,
  APP_ENV_FIREBASE_APP_ID,
};
